pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "build step"
            }
        }

        stage('Test') {
            steps {
                echo "this is test stage"
            }
        }
}
}

