pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/your-repo/your-project.git'
            }
        }

        stage('Test') {
            steps {
                echo "this is test stage"
            }
        }

